name: Test Api
on: [push, workflow_dispatch]
jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/simple-node-api
        ports:
          - 3001:3000
        env:
          MONGO_HOSTNAME: mongo
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Dump services context
        run: echo '${{ toJson(job.services) }}'

      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/users -H ''Content-Type: application/json'' -d ''{"username": "hello", "address":"dewd"}'''

      - name: Get users
        run: curl http://localhost:3001/api/users
